routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
})->middleware(['auth']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Manager')
    ->prefix('manager')
    ->name('manager.')
    ->middleware(['auth', 'auth.manager'])
    ->group(function () {
        Route::resource('/users', 'StaffsController');
        Route::resource('/items', 'ItemsController');
    });

resources/views/partials/alert.blade.php
@if(session('success'))
    <div class="alert alert-success" role="alert">
        {{ session('success') }}
    </div>
@endif

@if(session('warning'))
    <div class="alert alert-warning" role="alert">
        {{ session('warning') }}
    </div>
@endif

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/partials/menu.blade.php
@auth
    <ul class="navbar-nav mr-auto">
        {{-- show management dropdown if user is a manager --}}
        @if(Auth::user()->hasAnyRole('manager'))
            <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Management
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('manager.users.index') }}">Staffs</a>
                    <a class="dropdown-item" href="#">Sales</a>
                    <a class="dropdown-item" href="{{ route('manager.items.index') }}">Items</a>
                </div>
            </li>
        @endif
        {{-- show storage and orders if user is a staff --}}
        @if(Auth::user()->hasAnyRoles(['manager','staff']))
            <li class="nav-item active">
                <a class="nav-link" href="#">Storage</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">Orders</a>
            </li>
        @endif
    </ul>
@endauth

resources/views/partials/user.blade.php
<ul class="navbar-nav ml-auto">
    <!-- Authentication Links -->
    @guest
        <li class="nav-item">
            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
        </li>
        @if (Route::has('register'))
            <li class="nav-item">
                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
            </li>
        @endif
    @else
        <li class="nav-item dropdown">
            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                {{ Auth::user()->name }} <span class="caret"></span>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Profile</a>
                <a class="dropdown-item" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                      style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    @endguest
</ul>