routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
})->middleware(['auth']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Manager')
    ->prefix('manager')
    ->name('manager.')
    ->middleware(['auth', 'auth.manager'])
    ->group(function () {
        Route::resource('/users', 'StaffsController');
        Route::resource('/items', 'ItemsController');
    });

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }

    public function hasAnyRoles($roles)
    {
        return null !== $this->roles()->whereIn('name', $roles)->first();
    }

    public function hasAnyRole($role)
    {
        return null !== $this->roles()->where('name', $role)->first();
    }
}

app/Http/Controllers/Manager/ItemsController.php
<?php

namespace App\Http\Controllers\Manager;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Item;

class ItemsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('manager.items.index')
            ->with('items', Item::paginate(10));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('manager.items.edit')
            ->with(['item' => Item::find($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'price' => 'required|numeric|gte:0'
        ]);

        if ($validator->fails()) {
            return redirect()
                ->route('manager.items.edit', $id)
                ->withErrors($validator)
                ->withInput();
        }

        $item = Item::find($id);
        if ($item) {
            $item->name = $request->name;
            $item->price = $request->price;

            $item->save();
            return redirect()
                ->route('manager.items.index')
                ->with('success', 'Item updated successfully!');
        }

        return redirect()
            ->route('manager.items.index')
            ->with('warning', 'This item can not be edited.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Item::find($id);
        if ($item) {
//            $item->roles()->detach();
            $item->delete();
            return redirect()
                ->route('manager.items.index')
                ->with('success', 'Item has been deleted.');
        }

        return redirect()
            ->route('manager.items.index')
            ->with('warning', 'This item can not be deleted.');
    }
}

app/Http/Controllers/Manager/StaffsController.php
<?php

namespace App\Http\Controllers\Manager;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Role;
use Auth;
use Validator;

class StaffsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('manager.users.index')
            ->with('users',
                User::whereHas('roles', function ($q) {
                    $q->whereIn('name', ['staff']);
                })->paginate(10)
            );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('manager.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6|confirmed'
        ]);

        if ($validator->fails()) {
            return redirect()
                ->route('manager.users.create')
                ->withErrors($validator)
                ->withInput();
        }

        $staff = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password)
        ]);

        $staffRole = Role::where('name', 'staff')->first();
        $staff->roles()->attach($staffRole);

        return redirect()
            ->route('manager.users.index')
            ->with('success', 'A new staff created successfully!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('manager.users.edit')
            ->with(['user' => User::find($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6|confirmed'
        ]);

        if ($validator->fails()) {
            return redirect()
                ->route('manager.users.edit', $id)
                ->withErrors($validator)
                ->withInput();
        }

        $user = User::find($id);
        if ($user) {
            $user->name = $request->name;
            $user->email = $request->email;
            $user->password = bcrypt($request->password);

            $user->save();
            return redirect()
                ->route('manager.users.index')
                ->with('success', 'Staff updated successfully!');
        }

        return redirect()
            ->route('manager.users.index')
            ->with('warning', 'This staff can not be edited.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if ($user) {
            $user->roles()->detach();
            $user->delete();
            return redirect()
                ->route('manager.users.index')
                ->with('success', 'Staff has been deleted.');
        }

        return redirect()
            ->route('manager.users.index')
            ->with('warning', 'This staff can not be deleted.');
    }
}

resources/views/manager/users/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Create New Staff</div>

                    <div class="card-body">
                        <form action="{{ route('manager.users.store') }}" method="post">
                            @csrf
                            {{--create staff here--}}
                            <button type="submit" class="btn btn-primary">Create</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/manager/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Manage {{ $user->name }}</div>

                    <div class="card-body">
                        <form action="{{ route('manager.users.update', ['user' => $user->id]) }}" method="post">
                            @csrf
                            {{ method_field('PUT') }}
                            {{--update user details here--}}
                            <button type="submit" class="btn btn-primary">Update</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/manager/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Manage Staffs
                    </div>

                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Email</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($users->isEmpty())
                                <tr>
                                    <td>No staff found</td>
                                </tr>
                            @else
                                @foreach($users as $user)
                                    <tr>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>
                                            <a href="{{route('manager.users.edit', $user->id) }}">
                                                <button type="button" class="btn btn-primary">Edit</button>
                                            </a>
                                        </td>
                                        <td>
                                            <form action="{{route('manager.users.destroy', $user->id) }}" method="POST">
                                                @csrf
                                                {{ method_field('DELETE') }}
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                        {{ $users->links() }}
                        <a href="{{route('manager.users.create') }}">
                            <button type="button" class="btn btn-primary">Create New Staff</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection